@startuml
hide footbox
skinparam roundcorner 20
skinparam handwritten true
skinparam backgroundcolor transparent
skinparam minClassWidth 100

skinparam note {
  FontName Impact
}

object City {
    String : name
    List<Bar> : bars
    List<Restaurant> : restaurants
}

object Bar {
    String : name
    City: city
}

object Restaurant {
    String : name
    City: city
    String: cuisine
}

City --{ Bar
City --{ Restaurant
@enduml